### ISSUE TITLE
Problems in compilation

### ISSUE THREAD

**Issue by tan45power** [nppc/HotAirGunController#2] opened 2019-12-13 15:08 UTC
Thank you for sharing. I'm a beginner. I encountered some problems during compilation. Is it caused by my lack of library files?Which version of the library file should I use?  Can you give me some advice? At the beginning of compilation, it was prompted that pid_v1 and u8g2 were missing. I did not prompt after downloading and installing from the Internet. What I installed was  Arduino 1.8.10, thank you
'HotAirGunFirmware:141:2: error: 'fan_logo' was not declared in this scope ，HotAirGunFirmware:154:2: error: 'WDT_Init' was not declared in this scope，HotAirGunFirmware.ino:154:2: note: suggested alternative: 'WDT_vect'，
HotAirGunFirmware:172:2: error: 'showMainData' was not declared in this scope，
config:49:3: error: 'WDT_Init' was not declared in this scope，
config.ino:49:3: note: suggested alternative: 'WDT_vect'，
'showMainData' was not declared in this scope，max31855:80:1: error: expected declaration before '}' token.

**Comment by nppc** [comment] 2019-12-13 16:17
I suppose that you did not extracted all files from the archive. Please extract them to one directory named HotAirGunFirmware. Then try to compile again. Use latest versions of libraries (what I think you  doing already)

**Comment by hansrobothans** [comment] 2021-04-14 04:25
我也和tan45power一样遇到了同样的问题
I had the same problem of tan45power

**Comment by hansrobothans** [comment] 2021-04-14 04:52
After modification, I have solved the problem in the program. If you need, you can give me your email and I will send it to you @ @tan45power

**Comment by nppc** [comment] 2021-04-14 05:28
Thanks. You can create a merge request for the changes.

**Comment by hansrobothans** [comment] 2021-04-14 06:37
I will not merge……

**Comment by zuhair01** [comment] 2021-08-15 15:52
do you have a solution!

**Comment by tan45power** [comment] 2021-08-16 05:52
> 
> 
> 经过修改，我已经解决了程序中的问题。如果你需要，你可以给我你的电子邮件，我会发给你@@tan45power

Thanks.@hansrobothans  gooyyy2@gmail.com , I found that the version provided by @ Dmitry supranov can run in contributors of this project,@zuhair01

**Comment by nppc** [comment] 2021-08-16 07:17
For some reason I can't reproduce your issues. I have Arduino IDE 1.8.12. Could you please explain what steps are you doing?
Please show me all your output from Arduino IDE. Usually the first lines in the errors give the root cause of the issue.

**Comment by zuhair01** [comment] 2021-08-16 12:19
Arduino: 1.8.15 (Windows 10), Board:
C:\Users\xxxxxxx\Downloads\HotAirGunController-master eeeeee\HotAirGunController-master\HotAirGunFirmware\HotAirGunFirmware.ino: In function 'void setup()':

HotAirGunFirmware:141:2: error: 'fan_logo' was not declared in this scope

  fan_logo();

  ^~~~~~~~

C:\Users\xxxxxxx\Downloads\HotAirGunController-master eeeeee\HotAirGunController-master\HotAirGunFirmware\HotAirGunFirmware.ino: In function 'void loop()':

HotAirGunFirmware:154:2: error: 'WDT_Init' was not declared in this scope

  WDT_Init(); // keep system alive

  ^~~~~~~~

C:\Users\xxxxxxx\Downloads\HotAirGunController-master eeeeee\HotAirGunController-master\HotAirGunFirmware\HotAirGunFirmware.ino:154:2: note: suggested alternative: 'WDT_vect'

  WDT_Init(); // keep system alive

  ^~~~~~~~

  WDT_vect

HotAirGunFirmware:172:2: error: 'showMainData' was not declared in this scope

  showMainData();

  ^~~~~~~~~~~~

C:\Users\xxxxxxx\Downloads\HotAirGunController-master eeeeee\HotAirGunController-master\HotAirGunFirmware\config.ino: In function 'void configureParams()':

config:49:3: error: 'WDT_Init' was not declared in this scope

   WDT_Init();

   ^~~~~~~~

C:\Users\xxxxxxx\Downloads\HotAirGunController-master eeeeee\HotAirGunController-master\HotAirGunFirmware\config.ino:49:3: note: suggested alternative: 'WDT_vect'

   WDT_Init();

   ^~~~~~~~

   WDT_vect

C:\Users\xxxxxxx\Downloads\HotAirGunController-master eeeeee\HotAirGunController-master\HotAirGunFirmware\encoder.ino: In function 'void waitUntilButtonReleased()':

encoder:76:4: error: 'WDT_Init' was not declared in this scope

    WDT_Init();

    ^~~~~~~~

C:\Users\xxxxxxx\Downloads\HotAirGunController-master eeeeee\HotAirGunController-master\HotAirGunFirmware\encoder.ino:76:4: note: suggested alternative: 'WDT_vect'

    WDT_Init();

    ^~~~~~~~

    WDT_vect

C:\Users\xxxxxxx\Downloads\HotAirGunController-master eeeeee\HotAirGunController-master\HotAirGunFirmware\max31855.ino: At global scope:

max31855:80:1: error: expected declaration before '}' token

 }

 ^

exit status 1

'fan_logo' was not declared in this scope



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by nppc** [comment] 2021-08-16 12:57
Ok. I will try to play with code later today...

пн, 16 авг. 2021 г. в 14:19, zuhair01 ***@***.***>:

**Comment by nppc** [comment] 2021-08-16 13:32
Thank you all for the information provided. Compilation issue should be fixed now.

**Closed as completed by nppc** 2021-08-16 13:32 UTC
